language:
  - objective-c

env:
  - NODE_VERSION="6.11.4"
  - NODE_VERSION="8.6.0"

before_install:

install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm i -g npm@latest
  - npm install
script:
  - npm run test

notifications:
  email: false
